name: Deploy Azure Function App

on:
  push:
    branches:
      - master  # or 'main' if you're using 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python test.py

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: html-resume
        template: template.json
        parameters: parameters.json
        failOnStdErr: false

    - name: Zip Azure Function App code
      run: zip -r functionapp.zip .

    - name: Deploy to Azure Function App using CLI
      uses: azure/cli@v1
      with:
        inlineScript: |
          az functionapp deployment source config-zip \
            --name resumevisitor-fn \
            --resource-group html-resume \
            --src functionapp.zip
