name: Deploy Azure Function App

on:
  push:
    branches:
      - master  # or 'main' if you're using 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python test.py

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template (secure)
      uses: azure/cli@v1
      with:
        azcliversion: '2.72.0'
        inlineScript: |
          # Validate template (no overrides)
          az deployment group validate \
            --resource-group html-resume \
            --template-file template.json \
            --parameters @parameters.json \
            --only-show-errors

          # Deploy template
          az deployment group create \
            --resource-group html-resume \
            --template-file template.json \
            --parameters @parameters.json \
            --only-show-errors

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: resumevisitor-fn  
        package: '.'
