name: Deploy Azure Function App

on:
  push:
    branches:
      - master  # or 'main' if you're using 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest test.py -v

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template (secure)
      uses: azure/cli@v1
      with:
        azcliversion: '2.72.0'
        inlineScript: |
          # Validate template (no overrides)
          az deployment group validate \
            --resource-group html-resume \
            --template-file template.json \
            --parameters @parameters.json \
            --only-show-errors

          # Deploy template
          az deployment group create \
            --resource-group html-resume \
            --template-file template.json \
            --parameters @parameters.json \
            --only-show-errors

    - name: Build function app
      run: |
        # Clean up any local settings that shouldn't be deployed
        if [ -f "local.settings.json" ]; then
          echo "Backing up local.settings.json"
          cp local.settings.json local.settings.json.bak
        fi
        
        # Ensure host.json is present
        if [ ! -f "host.json" ]; then
          echo "Error: host.json is missing"
          exit 1
        fi

    # Use Azure CLI to deploy instead of functions-action
    - name: Deploy Function App with Azure CLI
      uses: azure/cli@v1
      with:
        azcliversion: '2.72.0'
        inlineScript: |
          # Zip the function app
          zip -r function-app.zip . -x "*.git*" "*.github*" "*test*" "*local.settings.json*"
          
          # Deploy using Azure CLI
          az functionapp deployment source config-zip \
            --resource-group html-resume \
            --name resumevisitor-fn \
            --src function-app.zip